server:
  port: 8082
spring:
  application:
    name: customer-service
  jpa:
    database: hsql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org:
#      springframework: DEBUG